### PR TITLE
Support VAT codes in the United Kingdom of Great Britain and Northern Ireland

### LINKED ISSUE #8: UK VAT numbers can no longer be validated?
According to https://ec.europa.eu/taxation_customs/vies/
> As of 01/01/2021, the VoW service to validate UK (GB) VAT numbers ceased to exist while a new service to validate VAT numbers of businesses operating under the Protocol on Ireland and Northern Ireland appeared. These VAT numbers are starting with the “XI” prefix, which may be found in the “Member State / Northern Ireland” drop down under the new entry “XI-Northern Ireland”. Moreover, any quote of “Member State” is replaced by “Member State / Northern Ireland” and any quote of “MS” is replaced by “MS / XI”. All traders seeking to validate UK (GB) VAT numbers may address their request to the UK Tax Administration.

### PR DESCRIPTION
**Pull request by davel**
I have added support for checking "GB" and "XI" VAT numbers.

* `GB` codes are checked via HMRC's API (see https://github.com/hmrc/vat-api/issues/678 )
* `XI` codes, which are for Northern Irish companies, are checked via VIES. Such companies should also be visible with a `GB` prefix.

I have also made some minor tidy ups and Kwalitee fixes.

Closes https://github.com/bigpresh/Business-Tax-VAT-Validation/issues/8

### CODE REVIEW

**Comment by bigpresh** [comment]
Fantastic stuff, thank you!

**Review by bigpresh — APPROVED** [review]

**Comment by bigpresh** [comment]
This is heading to CPAN as trial release 1.13_01 for CPAN smokers and interested users to test; as long as there are no problems reported, I'll promote it to a new stable release as 1.20 soon.

Many thanks again!

**Comment by bigpresh** [comment]
This code has been on CPAN for a few days: https://metacpan.org/release/BIGPRESH/Business-Tax-VAT-Validation-1.13_01

CPAN testers results look good: http://matrix.cpantesters.org/?dist=Business-Tax-VAT-Validation+1.13_01

So, I plan to get a new stable release out soon with it in.

**Comment by davel** [comment]
Thank for you putting a release together!

In the POD where you have credited me, there is a missing `=`, slightly breaking it, https://metacpan.org/pod/release/BIGPRESH/Business-Tax-VAT-Validation-1.13_01/lib/Business/Tax/VAT/Validation.pm#CREDITS

Could you also credit my customer, GoDaddy?

**Comment by bigpresh** [comment]
Good catch thanks - fixed the credit in fc6c7ee5bd72cbf3e8ca9db29d8ec25fbcb340ff

**Comment by bigpresh** [comment]
Stable release 1.20 is now on its way to CPAN.

**Pull request merged**
